GROQ_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyAlCNCGTafu5tABc9X0P_4thUSTQ_fq_LU"
SUPABASE_URL = "https://wqsfstjoeublcdgdbyza.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxc2ZzdGpvZXVibGNkZ2RieXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTE1NjQsImV4cCI6MjA3MDg4NzU2NH0.rfzDidImtzGEL7gyDRyK05XLZgZPJUBc40eQah-Ahdw"
PG_HOST = "aws-1-sa-east-1.pooler.supabase.com"
PG_PORT = "6543"
PG_DATABASE = "postgres"
PG_USER = "postgres.wqsfstjoeublcdgdbyza"
PG_POOL_MODE = "transaction"
PG_PASSWORD = "TI_omni@2020"
